### ISSUE TITLE
Allow local network access?

### ISSUE THREAD

**Issue by csm10495** [wiorca/docker-pia#5]
I was trying to use this along with transmission-qt inside of a docker-compose stack:

```
---
version: "3.5"

services:
  docker-pia:
    image: wiorca/docker-pia
    container_name: docker-pia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PIA_USERNAME=p...
      - PIA_PASSWORD=<REDACTED>
      - PIA_DEBUG_LOGGING=false
      - PIA_PROTOCOL=openvpn
      - PIA_PORT_FORWARD=false
      - PIA_REGION=auto
    volumes:
      - /location/on/host:/config
    dns:
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    ports:
      # for transmission
      - 9091:9091
      - 51413:51413
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      #- TRANSMISSION_WEB_HOME= #optional
      #- USER= #optional
      #- PASS= #optional
      #- WHITELIST= #optional
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional
    volumes:
      # MY_PATH:CONTAINER_PATH
      - /tmp/config:/config
      - /tmp/downloads:/downloads
      - /tmp/watch:/watch

    network_mode: service:docker-pia
    restart: unless-stopped


volumes:
  pia:
  pia-shared:
```

I couldn't seem to access transmission's port 9091. I'm guessing that PIA is doing something to block local network access. Is there a setting to overcome this? Thanks!
